### ISSUE TITLE
[!] (plugin rollup-plugin-obfuscator) RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by FDiskas** [getkey/rollup-plugin-obfuscator#2] opened 2021-02-14 12:22 UTC
error says nothing more
```
[!] (plugin rollup-plugin-obfuscator) RangeError: Maximum call stack size exceeded
src\core\server\server.ts
RangeError: Maximum call stack size exceeded
    at Object.getMetadata (***\node_modules\reflect-metadata\Reflect.js:352:29)
    at o.getRandomGenerator (***\server\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\decorators\Initializable.ts:58:30)
    at o.apply (***\server\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\utils\RandomGenerator.ts:44:21)
    at o.getRandomInteger (***\server\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\decorators\Initializable.ts:61:39)
    at o.generateNext (***\server\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\HexadecimalIdentifierNamesGenerator.ts:31:52)
```

**Comment by getkey** [comment] 2021-02-14 21:56
This is an error generated by javascript-obfuscator, and it's not caused by rollup-plugin-obfuscator, so I will close this issue. Could you open an issue [upstream](https://github.com/javascript-obfuscator/javascript-obfuscator)?

I have encountered this error myself at one point, as a workaround you can try increasing the Node.js memory with `env NODE_OPTIONS='--max-old-space-size=3072' rollup -c rollup.config.prod.js`.

**Closed by getkey** 2021-02-14 21:56 UTC
